#!/bin/sh

set -e

if [ ! -x "$(which lxc-info 2>/dev/null)" ]
then
	echo "E: lxc-info - no such file"
	exit 1
fi

for _STATUS in RUNNING STOPPED
do
	echo ${_STATUS}

	for _CONTAINER in $(lxc-ls | sort -u)
	do
		if lxc-info -n ${_CONTAINER} 2>&1 | grep -qs "${_STATUS}"
		then
			echo -n "  ${_CONTAINER}"

			if [ -e /etc/lxc/auto/${_CONTAINER} ]
			then
				echo " (auto)"
			else
				echo
			fi
		fi
	done

	echo
done
