#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ -e "${_PRESEED_FILE}" ]
then
	# user specified preseed file through commandline option
	db_set linux-container/preseed-file "${_PRESEED_FILE}"
	db_fset linux-container/preseed-file seen true
else
	# ask user for a preseed file
	db_settitle linux-container/title
	db_input high linux-container/preseed-file || true
	db_go

	db_get linux-container/preseed-file
	_PRESEED_FILE="${RET}" # string (w/ empty)
fi

echo "_PRESEED_FILE=\"${_PRESEED_FILE}\"" >> "${_TMPDIR}/debconf.default"

db_stop
