#!/bin/sh

set -e

if [ -e "${_TMPDIR}/debconf.default" ]
then
	. "${_TMPDIR}/debconf.default"
fi

if [ -e "${_PRESEED_FILE}" ]
then
	# Apply user specified preseed file
	debconf-set-selections "${_PRESEED_FILE}"
fi
