.\" lxc-halt(1) - shutdown a Linux Container
.\" Copyright (C) 2006-2011 Daniel Baumann <daniel.baumann@progress-technologies.net>
.\"
.\" lxc-halt comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
.\" This is free software, and you are welcome to redistribute it
.\" under certain conditions; see COPYING for details.
.\"
.\"
.TH LXC 1 2011\-11\-06 0.7.5-4 "Linux Containers"

.SH NAME
\fBlxc\-halt\fR \- shutdown Linux Containers by state

.SH SYNOPSIS
\fBlxc\-halt\fR \fICONTAINER\fR

.SH DESCRIPTION
\fBlxc\-halt\fR shuts down a Linux Container by not killing all processes of it like lxc\-stop does. It does an ordinary shutdown by issueing a switch to runlevel 0 within the container.

.SH OPTIONS
.IP "\fICONTAINER\fR" 4
specifies a Linux Container in the LXC path (default /var/lib/lxc).

.SH SEE ALSO
\fIlxc\fR(7),
\fIlxc\fR(1),
\fIlxc\-list\fR(1).

.SH BUGS
Bugs can be reported by submitting a bugreport for the lxc package in the Debian Bug Tracking System at <\fIhttp://bugs.debian.org/\fR> or by writing a mail to the author.

.SH AUTHOR
lxc\-halt was written by Daniel Baumann <\fIdaniel.baumann@progress-technologies.net\fR>.
