.\" lxc-list(1) - list Linux Containers by state
.\" Copyright (C) 2006-2011 Daniel Baumann <daniel.baumann@progress-technologies.net>
.\"
.\" lxc-list comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
.\" This is free software, and you are welcome to redistribute it
.\" under certain conditions; see COPYING for details.
.\"
.\"
.TH LXC 1 2011\-11\-04 0.7.5-3 "Linux Containers"

.SH NAME
\fBlxc\-list\fR \- list Linux Containers by state

.SH SYNOPSIS
\fBlxc\-list\fR

.SH DESCRIPTION
\fBlxc\-list\fR lists Linux Containers by state.

.SH OPTIONS
lxc\-list has no options.

.SH SEE ALSO
\fIlxc\fR(7),
\fIlxc\fR(1).

.SH BUGS
Bugs can be reported by submitting a bugreport for the lxc package in the Debian Bug Tracking System at <\fIhttp://bugs.debian.org/\fR> or by writing a mail to the author.

.SH AUTHOR
lxc\-list was written by Daniel Baumann <\fIdaniel.baumann@progress-technologies.net\fR>.
